const constants = {
    ENTER_INPUT_CODE: 'ENTER_INPUT_CODE',
    ENTER_INPUT_NUMBER: 'ENTER_INPUT_NUMBER',
    INVALID_NUMBER: 'INVALID_NUMBER',
    NUMBER_SENT: 'NUMBER_SENT',
    SENDING_ERROR: 'SENDING_ERROR',
    SENDING_NUMBER: 'SENDING_NUMBER',
    SUBMIT_CODE: 'SUBMIT_CODE',
    SUBMIT_NUMBER: 'SUBMIT_NUMBER',
};
export default constants;